# -*- coding:utf-8-unix -*-
#+LANGUAGE:  zh
#+TITLE:     纪秀峰_个人简历
#+AUTHOR:    纪秀峰
#+EMAIL:     jixiuf@gmail.com
#+DATE:     2012-03-14 三
#+DESCRIPTION:个人简历
#+KEYWORDS: 个人简历
#+OPTIONS:   H:2 num:nil toc:nil \n:t @:t ::t |:t ^:nil -:t f:t *:t <:t
#+TAGS:
* Word 版简历
+  [[file:~/Documents/org/src/download/JiXiufeng.doc][纪秀峰.doc]]
* 基本信息
  |------------+--------------------|
  | 电    话   | 13522419247　      |
  | 出生年月   | 1989-01            |
  | E-mail     | jixiuf@qq.com　    |
  | 英语水平   | 六级460            |
  | 证    书   | 数据库三级         |
  | 毕业院校   | 青岛科技大学       |
  | 学    历   | 本科 2007-9~2011-7 |
  | 户口所在地 | 山东青岛           |
  | 现居住地   | 北京海淀区         |
* 择业目标：
  + Golang/Erlang 服务端 开发工程师
* 自我介绍：
GitHub个人主页：            https://github.com/jixiuf
公司Golang部分开源代码： https://github.com/0studio （90%以上是我提交）
Erlang个人代码仓库:       https://github.com/jixiuf/helloerlang
EmacsWiki个人主页：      http://emacswiki.org/Joseph
个人博客:                 http://jixiuf.github.com/
自学能力强，所有计算机知识均为自学。以上几个网址是个人成果的展示，
Erlang个人代码仓库为
学习Erlang过程中写的一些代码;
 EmacsWiki个人主页  为我为Emacs开源社区贡献的代码。
* 专业技能：
+ 两年golang 游戏后端开发经验（2014-3~2016-1）
+ 一年erlang 游戏后端开发经验（2012-9 ~ 2014~3）
+ 两年Emacs编辑器使用经验，熟练掌握Emacs Lisp语言，为emacs开源社区贡献过代码，
   其中主要代码放在[[http://www.emacswiki.org/emacs/Joseph]] 开发用的 erlang-dired-mode.el ，修改增强erlang Emacs IDE distel  distel中文介绍
+ 熟悉java、eclipse 写过插件 https://github.com/emacs-java/eclipse_goto_editor
+ 简单了解 python
  用其做过 游戏管理后台

* 开发经验：
**  2014-3~2016-1
   近两年在雪狸主要参与了 手机游戏《超神传奇》 《点点大战》《casino 街
   机电玩大师/老虎机大师/诈金花大师》等几款游戏的服务端开发。最初后端
   只我一人， 基本架构由我设计主要语言 golang， 数据存储选用mysql 为应
   对高并发做了主从备份，且进行了mysql分库设计，golang GC较差 故用
   memcache 作缓存，排行相关使用redis，游戏进程做到了水平可扩展。即可
   以任意增加服务器进程数量，使用了etcd 来做服务发现及负载均衡

** 页游桃园外传项目(2012-2~2012-9)
   在乐元素公司旗下桃园外传项目组内负责erlang服务器端代码的编写,有erlang连
   mysql memcached等数据库的经验，了解 memcached、redis的协议并尝试
   用erlang实现与之连接,有一定的代码积累及调优经验.

**      海华生产管理系统(2011-7~2011-11)
    为青岛海华纤维有限公司（主要生产假发的半成品）编写生产管理系统 。主要分为三大模块：
1. 数据收集模块主要通过PDA(掌上电脑)条码扫描器从各袋半制品上的条码上扫描得到数
      据(进行盘点)、以及进行入库、出库操作。
2. PC 端，也同时可以进行入库、出库、数据统计、盘点、条形码打印等操作。PC端 主要
      使用C#、Silverlight WCF 等技术，后台数据库用SQL Server 2008。 前台界面使
      用Silverlight模仿Window7 操作系统，主要实现了用户权限控制、半制品（分为4
      个类似模块:半制品仓库、中间仓库、灌壁仓库、粉碎丝仓库）分别有入库、出库、
      统计、盘点等功能。
3. 条形码的生成通过调用TSC dll的打印功能实现。打印模块各独做成一个服务，放在服
      务器上，无论是扫描器端 、还是PC端都可以远程调用打印机进行条形码的打印
4. 我主要负责的tsc条码打印服务的编写、及条形码扫描器端3个出库画面、半制品盘点、
   灌壁盘点)(灌壁入库)、 等多个画面。PC端负责1个盘点画面(半制品盘点)、3个出库画
   面(中间仓库出库、灌壁出库、 粉碎丝出库、)、及半制品的管理(新增、更新、冻结、
   初始化库存)等操作。
