# -*- coding:utf-8-unix -*-
#+LANGUAGE:  zh
#+TITLE:     纪秀峰_个人简历
#+AUTHOR:    纪秀峰
#+EMAIL:     jixiuf@gmail.com
#+DATE:     2012-03-14 三
#+DESCRIPTION:个人简历
#+KEYWORDS: 个人简历
#+OPTIONS:   H:2 num:nil toc:nil \n:t @:t ::t |:t ^:nil -:t f:t *:t <:t
#+TAGS:
#+URI:         /author/
* Word 版简历
+  [[file:../download/JiXiufeng.doc][纪秀峰.doc]]
* 基本信息
  |------------+--------------------|
  | 电    话   | 17801090953        |
  | 出生年月   | 1989-01            |
  | E-mail     | jixiuf@qq.com　    |
  | 英语水平   | 六级460            |
  | 毕业院校   | 青岛科技大学       |
  | 学    历   | 本科 2007-9~2011-7 |
  | 户口所在地 | 山东青岛           |
  | 现居住地   | 北京海淀区         |
* 择业目标：
  + Golang 服务端 开发工程师
* 自我介绍：
GitHub个人主页：            https://github.com/jixiuf
公司Golang部分开源代码： https://github.com/0studio （90%以上是我提交）
Erlang个人代码仓库:       https://github.com/jixiuf/helloerlang
EmacsWiki个人主页：      http://emacswiki.org/Joseph
个人博客:                 http://jixiuf.github.io
以上几个网址是个人成果的展示，
Erlang个人代码仓库为学习Erlang过程中写的一些代码;
EmacsWiki个人主页  为我为Emacs开源社区贡献的代码。
* 专业技能：
+ 两年golang 游戏后端开发经验（2014-3~2016-1）
+ 一年erlang 游戏后端开发经验（2012-9 ~ 2014~3）
+ 熟悉java、eclipse 写过插件 https://github.com/emacs-java/eclipse_goto_editor
+ 简单了解python,用其做过 游戏管理后台
+ 熟悉linux开发环境，两年Emacs编辑器使用经验，为emacs开源社区贡献过代码，


* 开发经验：
ο	（2016-2~2017-7）就职于北京纳加科技有限公司
跟上个公司认识的朋友一起创业，目前在appstore仍可下载到的游戏
<<那家炸金花>>，主要负责服务端架构设计及代码编写，采用的架构基本继承上个公司所设计的那一套 golang+mysql+etcd+memcached+redis。
ο	 (2014-3~2016-2)就职于北京雪狸科技有限公司
前期一人负责游戏后端的架构设计与代码编写，采用Golang作为后端语言
两年内开发了两款手游<<超神传奇>>与<casino街机电玩大师>>
等几款游戏的服务端开发。最初后端只我一人， 基本架构由我设计
    主要语言 golang， 数据存储选用mysql 为应对高并发做了主从备份，且进行了mysql分库设计，golang GC较差 故用memcache 作缓存，排行榜相关使用redis存储，。即可以任意增加服务器进程数量，使用了etcd 来做服务发现及负载均衡，使游戏进程水平可扩展，可动态增加游戏进程数量。

ο	网页游戏<<乱世诛魔>>及<<兰陵王>> (Erlang) (2012-9~2014-2)
   乱世诛魔游戏在腾讯游戏平台目前已开服700多个。 在乱世诛魔项目中主要参与游戏服务端代码的编写，实现策划设计的新功能。 优化改造了此项目中读取策划文档数据的方式，加快了服务端程序的启动速度。 之后转到新项目组<<兰陵王>>,在<<乱世诛魔>>项目代码基础上进行开发。 对代码进行了较大改造 ，数据存储由原来的mnesia改成mysql,编写了底层连接mysql 数据库相关的代码，并对大量游戏基础模块的数据存储进行改造,改造完成之后<<兰陵王>> 项目正式立项， 与其他成员一些完成新的游戏逻辑的编写


** 页游桃园外传项目(2012-2~2012-9)
   在乐元素公司旗下桃园外传项目组内负责erlang服务器端代码的编写,有erlang连
   mysql memcached等数据库的经验，了解 memcached、redis的协议并尝试
   用erlang实现与之连接,有一定的代码积累及调优经验.

