# -*- coding:utf-8-unix -*-
#+LANGUAGE:  zh
#+TITLE:     纪秀峰_个人简历
#+AUTHOR:    纪秀峰
#+EMAIL:     jixiuf@gmail.com
#+DATE:     2012-03-14 三
#+DESCRIPTION:个人简历
#+KEYWORDS: 个人简历
#+OPTIONS:   H:2 num:nil toc:nil \n:t @:t ::t |:t ^:nil -:t f:t *:t :t
#+TAGS:
#+URI:         /author/
* Word 版简历
+  [[file:../download/JiXiufeng.doc][纪秀峰.doc]]
* 基本信息
  |------------+--------------------|
  | 电    话   | 17801090953        |
  | 出生年月   | 1989-01            |
  | E-mail     | jixiuf@qq.com　    |
  | 英语水平   | 六级460            |
  | 毕业院校   | 青岛科技大学       |
  | 学    历   | 本科 2007-9~2011-7 |
  | 户口所在地 | 山东青岛           |
  | 现居住地   | 北京海淀区         |
* 择业目标：
  + Golang 服务端 开发工程师
* 自我介绍：
GitHub个人主页：            https://github.com/jixiuf
公司Golang部分开源代码： https://github.com/0studio （90%以上是我提交）
Erlang个人代码仓库:       https://github.com/jixiuf/helloerlang
EmacsWiki个人主页：      http://emacswiki.org/Joseph
个人博客:                 http://jixiuf.github.io
以上几个网址是个人成果的展示，
Erlang个人代码仓库为学习Erlang过程中写的一些代码;
EmacsWiki个人主页  为我为Emacs开源社区贡献的代码。
* 专业技能：
+ 三年半年golang 游戏后端开发经验,了解docker、etcd、vitess等开源项目（2014-3~）
+ 两年erlang 游戏后端开发经验（2012-3 ~ 2014~3）
+ 熟悉java、eclipse 写过插件 https://github.com/emacs-java/eclipse_goto_editor
+ 简单了解python,用其做过 游戏管理后台
+ 熟悉linux开发环境，两年Emacs编辑器使用经验，为emacs开源社区贡献过代码，


* 开发经验：
-	（2016-2~2017-7）就职于北京纳加科技有限公司
跟上个公司认识的朋友一起创业，目前在appstore仍可下载到的游戏
那家炸金花，主要负责服务端架构设计及代码编写，采用的架构基本继承上个公司所设计的那一套 golang+mysql+etcd+memcached+redis。
-	 (2014-3~2016-2)就职于北京雪狸科技有限公司
    前期一人负责游戏后端的架构设计与代码编写，采用Golang作为后端语言
    两年内开发了两款手游超神传网页游戏乱世诛魔及兰陵王奇与casino街机电玩大师
    等几款游戏的服务端开发。最初后端只我一人。
    基本架构由我设计,主要语言 golang， 数据存储选用mysql 为应对高并发根据玩家ID进行了mysql分库设计。
    golang 前期GC较差 故用memcache 作缓存，以减少go游戏进程的内存消耗,减少GC卡顿。
    排行榜相关使用redis存储,及玩家操作、流水数据转化成sql语句 push 到redis队列中，供以后pop到mysql 做后期数据统计与分析。
    使用了etcd 来做服务发现及负载均衡,游戏进程启动时会将自身信息注册到etcd中，
    玩家认证用的进程，会监听etcd的变化，并根据其中各游戏进程的负载信息来将玩家平分到游戏进程上。
    即可以根据玩家数量调整服务器进程数量，使游戏进程水平可扩展。

-  网页游戏乱世诛魔及兰陵王 就职于北京纯白科技(Erlang) (2012-6~2014-2)
   乱世诛魔游戏在腾讯游戏平台目前已开服700多个。 在乱世诛魔项目中主要参与游戏服务端代码的编写，实现策划设计的新功能。
   优化改造了此项目中读取策划文档数据的方式，加快了服务端程序的启动速度。
   之后转到新项目组兰陵王,在乱世诛魔项目代码基础上进行开发。
   对代码进行了较大改造 ，数据存储由原来的mnesia改成mysql,编写了底层连接mysql 数据库相关的代码，并对大量游戏基础模块的数据存储进行改造,
   改造完成之后兰陵王 项目正式立项， 与其他成员一些完成新的游戏逻辑的编写


-  海华生产管理系统 (C#)软脑离岸资源(青岛)有限公司 (2010-10~2012-9)
    2010~10月 此 实习，为青岛海华纤维有限公司（主要生产假发的半成品）编写生产管理系统 。
    主要分为三大模块，
    1. 数据收集模块通过PDA(掌上电脑)条码扫描器从各袋半制品上的行条码上扫描得到数据(进行盘点)、以及进行入库、出库操作。
    2. PC 端，也同时可以进行入库、出库、数据统计、盘点、条形码打印、等操作。
        PC端 主要使用C#.net、silverlight WCF 等技术，后台数据库用SQL Server 2008。
        前台界面使用silverlight模仿Window7 操作系统界面，主要实现了用户权限控制、半制品在半制品仓库、中间仓库、灌壁仓库、粉碎丝仓库中的管理，分别有 入库、出库、在库信息、统计、盘点等功能。
    3. 条形码的生成通过调用TSC dll的打印功能实现。打印模块单独做成一个服务，放在服务器上，无论是扫描器端 、还是PC端都可以远程调用打印机进行条形码的打印。
        项目中，我主要负责的tsc条码打印服务的编写及条形码扫描器端出库(半制品出库、中间仓库出库、灌壁出库、粉碎丝出库)、盘点(半制品盘点、灌壁盘点)入库(灌壁入库)、等多个画面（共两人负责）。
        PC端负责1个盘点画面(半制品盘点)、3个出库画面(中间仓库出库、灌壁出库、粉碎丝出库、)、及基础数据中半制品的管理(新增、更新、冻结、初始化库存)等操作。

